version: "3.5"

x-logging:
  &default-loggin
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "2"

services:
  stackdriver-gathering:
    container_name: stackdriver-gathering
    image: telegraf:${TELEGRAF_VERSION}
    logging: *default-loggin
    restart: always
    labels:
      - "dekd.monitoring.app=stackdriver-gathering"
    environment:
      - TZ=Asia/Bangkok
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./telegraf/config:/etc/telegraf:ro
      - ./telegraf/credentials:/credentials:ro
